-- Перенос тем чат-бота (43 темы, 75 видео-манёвров) на интерактивную карту маршрута как отдельные точки. Часть 1/3 (точки 1-25)
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 8, 'Автодром Максимум', 'start', 55.478703, 65.3139812, 'https://global.s3.cloud.ru/vektor45/автодром%20максимум/автодром%20максимум-1.mp4', 'автодром максимум', 'автодром максимум', 'normal', 8, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 9, 'Баумана развороты (1/2)', 'u_turn', 55.4560886, 65.3136662, 'https://global.s3.cloud.ru/vektor45/Баумана3/Баумана3-1.mp4', 'Баумана развороты (1/2)', 'На данном видео будут вам будут показаны места для разворотов на улице Баумана. Внимательно слушайте задания инспектора! Могут дать задание развернуться как на перекрестке так и вне перекрестка', 'normal', 9, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 10, 'Баумана развороты (2/2)', 'u_turn', 55.4557886, 65.3136662, 'https://global.s3.cloud.ru/vektor45/баумана дальний разворот/баумана дальний разворот-1.mp4', 'Баумана развороты (2/2)', 'Если вдруг вы проехали все развороты на близлежайших перекрестках, место для разворота на перекрестке будет чуть дальше', 'normal', 10, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 11, 'Автомакс машиностроителей маневры (1/2)', 'other', 55.4401839, 65.3503326, 'https://global.s3.cloud.ru/vektor45/Остановка автомакс/Остановка автомакс-1.mp4', 'Постановка ТС параллельно тротуару, двигаясь по направлению вперед', 'На видео показаны маневры в Рябкого
Ориентир желтый магазин "Автомакс"', 'normal', 11, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 12, 'Автомакс машиностроителей маневры (2/2)', 'u_turn', 55.4398839, 65.3503326, 'https://global.s3.cloud.ru/vektor45/автомакс/автомакс-1.mp4', 'Автомакс машиностроителей маневры (2/2)', 'Развороты', 'normal', 12, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 13, 'Чернореченская (1/5)', 'u_turn', 55.4867797, 65.3206075, 'https://global.s3.cloud.ru/vektor45/Маневры черноречка/Маневры черноречка-1.mp4', 'Развороты Чернореченская', 'Все маневры на улице Чернореченская. На данной улице можно останавливаться везде. Места для разворотов вне перекрестка все удобные.', 'normal', 13, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 14, 'Чернореченская (2/5)', 'u_turn', 55.4866761, 65.3207502, 'https://global.s3.cloud.ru/vektor45/чернореч остановка ограничка/чернореч остановка ограничка-1.mp4', 'Разворот в ограниченном пространстве на ул.Чернореченская', 'Разворот ТС в ограниченном пространстве с использованием движения задним ходом', 'normal', 14, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 15, 'Чернореченская (3/5)', 'intersection', 55.4865083, 65.3206957, 'https://global.s3.cloud.ru/vektor45/дворы возле пятерочки рябкого/дворы возле пятерочки рябкого-1.mp4', 'Чернореченская (3/5)', 'На данный участок дороги вас могут завести для выполнения пункта "Проезд нерегулируемого перекрестка неравнозначных дорог" в экзаменационном листе', 'normal', 15, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 16, 'Чернореченская (4/5)', 'u_turn', 55.4865083, 65.3205193, 'https://global.s3.cloud.ru/vektor45/налево с огранички рябик/налево с огранички рябик-1.mp4', 'Чернореченская (4/5)', 'Выезд с разворота в ограниченном пространстве', 'normal', 16, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 17, 'Чернореченская (5/5)', 'u_turn', 55.4866761, 65.3204648, 'https://global.s3.cloud.ru/vektor45/чернореч остановка ограничка/чернореч остановка ограничка-1.mp4', 'Чернореченская (5/5)', 'Остановка и разворот в ограниченном пространствке', 'normal', 17, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 18, 'Садовая маневры', 'other', 55.4095733, 65.5350267, 'https://global.s3.cloud.ru/vektor45/Садовая/Садовая-1.mp4', 'Садовая маневры', 'Маневры на улице Садовая', 'normal', 18, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 19, 'улица Салавата Юлаева', 'other', 55.4962639, 65.329203, 'https://global.s3.cloud.ru/vektor45/Салавата Юлаева/Салавата Юлаева-1.mp4', 'Маневры Салавата', 'Маневры на Салавата Юлаева', 'normal', 19, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 20, 'Циолковского', 'other', 55.5001441, 65.3164354, 'https://global.s3.cloud.ru/vektor45/Циолковского/Циолковского-1.mp4', 'Циолковского', 'улица Циолковского, маневры', 'normal', 20, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 21, 'Автодром Максимум 2', 'start', 55.478703, 65.3139812, 'https://global.s3.cloud.ru/vektor45/автодром максимум-1.mp4', 'Автодром Максимум 2', 'Въезд на автодром максимум', 'normal', 21, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 22, 'улица Мальцева (1/3)', 'other', 55.4639423, 65.2674402, 'https://global.s3.cloud.ru/vektor45/Мальцева-7шк/Мальцева-7шк-1.mp4', 'улица Мальцева (1/3)', 'Маневры ул.Мальцева', 'normal', 22, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 23, 'улица Мальцева (2/3)', 'u_turn', 55.4637173, 65.2675701, 'https://global.s3.cloud.ru/vektor45/мальцева-фарафонова/мальцева-фарафонова-1.mp4', 'улица Мальцева (2/3)', 'Разворот на перекрестке Мальцева-Фарафонова', 'normal', 23, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 24, 'улица Мальцева (3/3)', 'other', 55.4637173, 65.2673103, 'https://global.s3.cloud.ru/vektor45/Генерала Дубынина 7школа/Генерала Дубынина 7школа-1.mp4', 'улица Мальцева (3/3)', '7 школа маневры', 'normal', 24, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 25, 'Иллизарова со стороны 6а', 'other', 55.4683299, 65.2881621, 'https://global.s3.cloud.ru/vektor45/Иллизарова 6мкрн/Иллизарова 6мкрн-1.mp4', 'Иллизарова со стороны 6а', 'Маневры на улице Иллизарова со стороны 6мкр', 'normal', 25, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 26, 'Баумана остановки, ближайший перекресток для разворота', 'u_turn', 55.4559386, 65.3136662, 'https://global.s3.cloud.ru/vektor45/баумана1/баумана1-1.mp4', 'Баумана остановки, ближайший перекресток для разворота', 'На данном видео показаны места для остановок, а так же разворот на ближайшем разрешенном перекрестке на ул. Баумана', 'normal', 26, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 27, 'Баумана ближайшее место для рвр', 'u_turn', 55.4559386, 65.3136662, 'https://global.s3.cloud.ru/vektor45/баумана2/баумана2-1.mp4', 'Баумана ближайшее место для рвр', 'Выполнение задания "Выберите ближайшее место для разворота - развернитесь"', 'normal', 27, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 28, 'Бурова Петрова таможня маневры', 'other', 55.4774466, 65.3357705, 'https://global.s3.cloud.ru/vektor45/бурова петрова/бурова петрова-1.mp4', 'Бурова Петрова таможня маневры', 'На данном видео показаны маневры на ул. Бурова Петрова (р-н Таможни)', 'normal', 28, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 29, 'Разворот в сторону трассы', 'u_turn', 55.4409357, 65.3421169, 'https://global.s3.cloud.ru/vektor45/в сторону трассы маневр/в сторону трассы маневр-1.mp4', 'Разворот в сторону трассы', 'Разворот, который дается после проезда односторонки ГАИ в прямом направлении', 'normal', 29, true);