INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 58, 'КОЛЬЦО 6а (1/3)', 'intersection', 55.4631294, 65.2557947, 'https://global.s3.cloud.ru/vektor45/кольцо 6а/кольцо 6а налево/кольцо 6а налево-1.mp4', 'КОЛЬЦО 6а (1/3)', 'Кольцо 6а', 'normal', 58, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 59, 'КОЛЬЦО 6а (2/3)', 'intersection', 55.4629044, 65.2559246, 'https://global.s3.cloud.ru/vektor45/кольцо 6а/кольцо 6а-1.mp4', 'КОЛЬЦО 6а (2/3)', 'Перекресток с круговым движением 6а мкр-н, маневры', 'normal', 59, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 60, 'КОЛЬЦО 6а (3/3)', 'intersection', 55.4629044, 65.2556648, 'https://global.s3.cloud.ru/vektor45/родькина кольцо сев/родькина кольцо сев-1.mp4', 'КОЛЬЦО 6а (3/3)', 'Поворот на кольце в 6 мкр-не', 'normal', 60, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 61, 'Перекресток Мальцева-Фарафонова', 'u_turn', 55.4637923, 65.2674402, 'https://global.s3.cloud.ru/vektor45/мальцева-фарафонова/мальцева-фарафонова-1.mp4', 'Перекресток Мальцева-Фарафонова', 'Разворот на перекрестке ул. Фарафонова-Мальцева', 'normal', 61, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 62, 'Родькина улица (1/2)', 'other', 55.468855, 65.2912759, 'https://global.s3.cloud.ru/vektor45/маневр родькина улица/маневр родькина улица-1.mp4', 'Родькина улица (1/2)', 'Улица Родькина', 'normal', 62, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 63, 'Родькина улица (2/2)', 'turn_left', 55.468555, 65.2912759, 'https://global.s3.cloud.ru/vektor45/родькина голикова налево/родькина голикова налево-1.mp4', 'Родькина улица (2/2)', 'Поворот налево с улицы Родькина, на пр.Голикова', 'normal', 63, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 64, 'Ограничка 6а', 'u_turn', 55.4629794, 65.2557947, 'https://global.s3.cloud.ru/vektor45/ограничка 6мкр/ограничка 6мкр-1.mp4', 'Ограничка 6а', 'Разворот в ограниченном пространстве 6а мкр-н', 'normal', 64, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 65, 'Ограничка LADA', 'u_turn', 55.4467523, 65.3588099, 'https://global.s3.cloud.ru/vektor45/ограничка LADA/ограничка LADA-1.mp4', 'ограничка LADA', 'Разворот в ограниченном пространстве на автосалоне Lada.
ул. Машиностроителей', 'normal', 65, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 66, 'Бурова петрова голикова', 'turn_left', 55.4774466, 65.3357705, 'https://global.s3.cloud.ru/vektor45/поворот налево голикова бурова/поворот налево голикова бурова-1.mp4', 'Бурова петрова голикова', 'Поворот налево на перекрестке Голикова-Бурова Петрова', 'normal', 66, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 67, 'Кузнецова', 'other', 55.4916709, 65.3073702, 'https://global.s3.cloud.ru/vektor45/кузнецова/кузнецова-1.mp4', 'Кузнецова', 'Маневры на улице Кузнецова', 'normal', 67, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 68, 'Пархоменко', 'other', 55.4911304, 65.2953012, 'https://global.s3.cloud.ru/vektor45/пархоменко/пархоменко-1.mp4', 'Пархоменко', 'Маневры ул.Пархоменко', 'normal', 68, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 69, 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (1/3)', 'u_turn', 55.4849602, 65.2229979, 'https://global.s3.cloud.ru/vektor45/поворот налево с мостостроителей на голикова/голикова-мостостроителей/голикова-мостостроителей-1.mp4', 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (1/3)', 'Разворот на перекрестке Голикова-Мостостроителей', 'normal', 69, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 70, 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (2/3)', 'turn_left', 55.4847352, 65.2231278, 'https://global.s3.cloud.ru/vektor45/поворот налево с мостостроителей на голикова/поворот налево с мостостроителей на голикова-1.mp4', 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (2/3)', 'Поворот налево с улицы Мостостроителей на ул. Голикова', 'normal', 70, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 71, 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (3/3)', 'u_turn', 55.4847352, 65.222868, 'https://global.s3.cloud.ru/vektor45/поворот налево с мостостроителей на голикова/разворот голикова-мостостроителей вне перекрестка/разворот голикова-мостостроителей вне перекрестка-1.mp4', 'ГОЛИКОВА-МОСТОСТРОИТЕЛЕЙ (3/3)', 'Разворот вне перекрестка', 'normal', 71, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 72, 'Разворот на знаке "Место для разворота" Голикова', 'u_turn', 55.4821689, 65.3261498, 'https://global.s3.cloud.ru/vektor45/разворот вне перекрестка голикова/разворот вне перекрестка голикова-1.mp4', 'Разворот на знаке "Место для разворота" Голикова', 'Пример разворота в месте, обозначенном знаком "Место для разворота"', 'normal', 72, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 73, 'Разворот на перекрестке первомайский витебского', 'u_turn', 55.461, 65.279, 'https://global.s3.cloud.ru/vektor45/разворот перекресток первомайский витебского/разворот перекресток первомайский витебского-1.mp4', 'Разворот на перекрестке первомайский витебского', 'Разворот на перекрестке пер.Первомайский-Витебского
(6а мкр-н)', 'normal', 73, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 74, 'Разворот на Голикова в месте не обозначенном знаком', 'u_turn', 55.4747853, 65.2995725, 'https://global.s3.cloud.ru/vektor45/разворот вне перекрестка голикова/разворот голикова вне перекрестка необозн/разворот голикова вне перекрестка необозн-1.mp4', 'Разворот на Голикова в месте не обозначенном знаком', 'Разворот в месте не обозначенном знаком "Место для разворота" на Голикова', 'normal', 74, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 75, 'Разворот на перекрестке у Реквиема Lada', 'u_turn', 55.4467523, 65.3588099, 'https://global.s3.cloud.ru/vektor45/разворот реквием/разворот реквием-1.mp4', 'Разворот на перекрестке у Реквиема Lada', 'Разворот на перекрестке вблизи "Lada" "Реквием" у авторынка', 'normal', 75, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 76, 'Поворот налево пер. Дзержинского-Баумана', 'turn_left', 55.4620162, 65.359261, 'https://global.s3.cloud.ru/vektor45/поворот налево на перекрестке баумана дзержинского/поворот налево на перекрестке баумана дзержинского-1.mp4', 'Поворот налево пер. Дзержинского-Баумана', 'Поворот налево на перекрестке Дзержинского-Баумана', 'normal', 76, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 77, 'Разворот на перекрестке Стрекоза', 'u_turn', 55.4410159, 65.3431555, 'https://global.s3.cloud.ru/vektor45/разворот стрекоза/разворот стрекоза-1.mp4', 'Разворот на перекрестке Стрекоза', 'Разворот на перекрестке вблизи ТЦ "Стрекоза"', 'normal', 77, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 78, 'пер.Первомайский', 'other', 55.4615, 65.278, 'https://global.s3.cloud.ru/vektor45/развороты первомайских фсб/развороты первомайских фсб-1.mp4', 'пер.Первомайский', 'Маневры на пер.Первомайский', 'normal', 78, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 79, 'Северный р-н ШТАНЫ', 'u_turn', 55.5153281, 65.3839199, 'https://global.s3.cloud.ru/vektor45/штаны северный и разворот/штаны северный и разворот-1.mp4', 'Северный р-н ШТАНЫ', 'Разворот и проезд У-образного перекрестка', 'normal', 79, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 80, 'Фарафонова', 'other', 55.4672316, 65.2574595, 'https://global.s3.cloud.ru/vektor45/фарафонова/фарафонова-1.mp4', 'Фарафонова', 'Маневры ул.Фарафонова', 'normal', 80, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 81, 'Тюленина', 'other', 55.4575572, 65.3022053, 'https://global.s3.cloud.ru/vektor45/тюленина маневры даль/тюленина маневры даль-1.mp4', 'Тюленина', 'Тюленина маневры', 'normal', 81, true);
INSERT INTO t_p22961065_vector_driving_instr.route_points (route_id, point_number, title, point_type, lat, lng, video_url, video_title, description, difficulty, sort_order, is_active) VALUES (1, 82, 'Черняховского', 'other', 55.4994609, 65.3327526, 'https://global.s3.cloud.ru/vektor45/черняховского все маневры/черняховского все маневры-1.mp4', 'Черняховского', 'Маневры на ул.Черняховского', 'normal', 82, true);